# Generated by Django 5.1 on 2024-11-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='defaltpassword', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
