# Generated by Django 5.1 on 2024-11-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='size',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.ImageField(choices=[(1, 'ORDER_CONFIRMED'), (2, 'ORDER_PROCSSED'), (3, 'ORDER_DELIVERD'), (4, 'ORDER_REJECTED')], default=0, upload_to=''),
        ),
    ]
