# Generated by Django 5.1 on 2024-11-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordereditem_size_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'ORDER_CONFIRMED'), (2, 'ORDER_PROCSSED'), (3, 'ORDER_DELIVERD'), (4, 'ORDER_REJECTED')], default=0),
        ),
    ]
